wheels:
  encoder_resolution: 878.4
  torque_constant: 1.17647
  pid:
    p: 0.0
    i: 0.005
    d: 0.0
  pwm_duty_limit: 100.0

mecanum_wheels: false

controller:
  wheel_radius: 0.0625
  wheel_separation: 0.358
  angular_velocity_multiplier: 1.76
  input_timeout: 500

battery_min_voltage: 10.0