wheels:
  encoder_resolution: 878.4
  torque_constant: 1.17647
  pid:
    p: 0.0
    i: 0.005
    d: 0.0
  pwm_duty_limit: 100.0

mecanum_wheels: true

controller:
  wheel_radius: 0.0635
  wheel_separation: 0.37
  wheel_base: 0.3052
  angular_velocity_multiplier: 1.0
  input_timeout: 500

battery_min_voltage: 10.0