/**:
  rosbridge_server:
    ros__parameters:
      default_call_service_timeout: 5.0
      call_services_in_new_thread: true
      send_action_goals_in_new_thread: true

/**:
  rosapi:
    ros__parameters:
      use_private_service_names: true
