/**:
  ros__parameters:
    video_device: /dev/video0
    pixel_format: YUYV
    output_encoding: rgb8
    image_size: [640, 480]
    time_per_frame: [1, 30]
    camera_info_url: package://leo_bringup/camera_info/leo_camera.yaml
