#!/usr/bin/env python3

import contextlib
from leo_fw.nodes import ParameterBridge
import rclpy

rclpy.init()

node = ParameterBridge()

with contextlib.suppress(KeyboardInterrupt):
    rclpy.spin(node)
