#!/usr/bin/env python3

import sys
import argparse

import leo_fw
from leo_fw.test_motors import MotorTestMode


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Test Leo Rover motors",
        epilog="ROS arguments can be passed after --ros-args, "
        "e.g. --ros-args -r __ns:=/leo",
    )

    parser.add_argument(
        "-m",
        dest="mode",
        type=MotorTestMode,
        choices=list(MotorTestMode),
        default="all",
        help="select test mode",
    )

    args, ros_args = parser.parse_known_args()

    leo_fw.test_motors(mode=args.mode, ros_args=[sys.argv[0]] + ros_args)


if __name__ == "__main__":
    main()
