#!/usr/bin/env python3

import sys
import argparse

import leo_fw
from leo_fw.test_hw import TestMode


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Test Leo Rover hardware",
        epilog="ROS arguments can be passed after --ros-args, "
        "e.g. --ros-args -r __ns:=/leo",
    )

    parser.add_argument(
        "-m",
        dest="hardware",
        type=TestMode,
        choices=list(TestMode),
        default="all",
        help="select test mode",
    )

    args, ros_args = parser.parse_known_args()

    sys.exit(leo_fw.test_hw(hardware=args.hardware, ros_args=[sys.argv[0]] + ros_args))


if __name__ == "__main__":
    main()
