name: CI-Iron

on:
  workflow_dispatch:
  push:
    branches:
      - iron
  pull_request:
    branches:
      - iron

env:
 ROS_DISTRO: iron

jobs:
  industrial_ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ROS_REPO: [testing, main]
    env:
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
        env:
          UPSTREAM_WORKSPACE: "github:LeoRover/leo_common-ros2#iron"
          PYLINT_CHECK: true
          PYLINT_ARGS: "--rcfile=src/leo_robot-ros2/.pylintrc"
